repos:
  - repo: local
    hooks:
      - id: fourmolu
        name: fourmolu
        entry: fourmolu --mode inplace
        language: system
        files: ^(src|test)/.*\.hs$

      - id: hlint
        name: hlint
        entry: hlint
        language: system
        files: ^(src|test)/.*\.hs$
