repos:
  - repo: local
    hooks:
      - id: fourmolu
        name: fourmolu (formatter)
        entry: fourmolu --mode inplace
        language: system
        files: '.*\\.(hs|hs-boot)$'

      - id: hlint
        name: hlint (linter)
        entry: hlint
        language: system
        files: '.*\\.(hs|hs-boot)$'