name: Format

on:
  pull_request:
    branches: ["*"]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: haskell-actions/run-fourmolu@v11
        with:
          version: "0.18.0.0"
          pattern: |
            **/*.hs
